# Generated by Django 2.2.1 on 2019-08-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='frist_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
