# Generated by Django 2.2.1 on 2019-08-23 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_profile_b_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='b_image',
            new_name='coverphoto',
        ),
    ]
